appdata: use appstreamcli for appdata validation
geigi/cozy pull request #796
Opened 2023-11-03 20:27 UTC by sabriunal

appstream-util is obsoleted by appstreamcli.

2023-11-03 20:27 UTC, sabriunal commented
Michael Catanzaro recommended the use of appstreamcli in [this comment](https://gitlab.gnome.org/World/eartag/-/merge_requests/95#note_1874726).
He also suggest removing the purism tags completely.

2023-11-29 15:09 UTC, rdbende requested changes

2023-11-29 15:09 UTC, rdbende commented on data/com.github.geigi.cozy.appdata.xml
> -  <url type="help">https://github.com/geigi/cozy/issues</url>
I think it should point to [`https://matrix.to/#/#cozy:gnome.org?via=matrix.org&via=gnome.org`](https://matrix.to/#/#cozy:gnome.org?via=matrix.org&via=gnome.org) instead

2023-11-29 21:31 UTC, rdbende approved these changes

2023-12-03 14:43 UTC, merged