Add option to reset book and remove from recents screen (#851)
geigi/cozy pull request #946
Opened 2024-07-25 17:59 UTC by Haaruun-I

Adds a 'Reset Book' button to both the context menu in the preview card and the book details page. 

For now all it does is remove the 'last_played' time to get it off the recents screen, but i'm not sure if it should also reset the playback progress.

Not sure about the wording of the options though, reset sounds like it should also clear your playback, but 'remove from recents' is too long.

Heres it in action, still cant get the icons to work (#852) current 'reset' icon is the back arrow also used for the seek bar
https://github.com/user-attachments/assets/081c234c-871b-45e0-a50d-50f64c6339f6

2024-07-26 12:51 UTC, geigi commented
Thanks for your contribution :) Removing books from the recent page again is a nice feature I think.

Some thoughts on the feature, haven't looked at the code yet:
- I agree with the wording as it is unclear what reset means and what it does. I would opt for the longer option "remove from recents" for the context menu
- A reset for the playback position (progress) is not really necessary in my opinion because you can just click on the first chapter and start again
- I would prefer to keep this option only in the context menu of the library view. The current action (removing from recent page) is completely unrelated to the book detail page. I also feel like providing this action a button which is almost as prominent as the play button is confusing.

2024-07-26 15:00 UTC, Haaruun-I commented
Alright!

2024-07-26 18:10 UTC, rdbende requested changes
I left a few comments, but it's mostly unneded code.
Thanks a lot for working on this, btw! I now have some hope that we can get some new contributors to the project 😊

2024-07-26 18:10 UTC, rdbende commented on cozy/ui/book_detail_view.py
> +            self.reset_button.show()
```suggestion
```

This isn't necessary.

2024-07-26 18:10 UTC, rdbende commented on cozy/ui/widgets/book_card.py
> +        # self.book.position = 0
```suggestion
```
Since we don't want to reset the playback position, this commented code will not be necssary.

2024-07-26 18:10 UTC, rdbende commented on data/ui/book_card.blp
> +    }
I think this item would be better above "Open in Files". It's more related to "Mark as Read" as bot of these options effect the book state.

2024-07-26 19:43 UTC, Haaruun-I commented
Thank you for the quick review! I use cozy allot, and i had some free time, so i just thought Id help out a bit. :D

2024-08-09 16:58 UTC, rdbende approved these changes
Hi @Haaruun-I! I fixed the issue you had to work around in your "Temporary UI Bugfix". Sorry about that, it was my bad. Somehow I didn't commit that hunk in one of my PRs.

2024-08-09 17:07 UTC, merged

2024-08-10 06:06 UTC, Haaruun-I commented
Thanks @rdbende! Dont know how I missed the `BookCardPlayButton` was right there :sweat_smile: